### PR TITLE
Add installation instructions.

### PR DESCRIPTION
**Pull request by teymour-aldridge**

### CODE REVIEW

**Comment by sagudev** [comment]
Hm on my computer I only needed to run `cargo install cargo-mach`

**Comment by teymour-aldridge** [comment]
You're right, sorry, I didn't realise the crate was on crates.io

**Comment by sagudev** [comment]
Could you also add crates io badge?

**Comment by teymour-aldridge** [comment]
yup

**Comment by sagudev** [comment]
Thanks

**Pull request merged**
